### PR TITLE
doc: Update supported expressions

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #.

## Rationale for this change

We added some more supported expressions. We should update the document.

### CODE REVIEW

**Comment by viirya** [comment]
cc @parthchandra @huaxingao

**Review by snmvaughan — APPROVED** [review]
LGTM

**Comment by huaxingao** [comment]
LGTM

**Review by huaxingao — APPROVED** [review]

**Comment by viirya** [comment]
cc @sunchao

**Comment by dbtsai** [comment]
Is there a document listing unsupported expressions that individuals could potentially work on if they're interested? Thank you.

**Comment by viirya** [comment]
> Is there a document listing unsupported expressions that individuals could potentially work on if they're interested? Thank you.

We don't have such document. Spark expressions are too many so the unsupported list might be very long.

We can probably list some frequently used expressions which are not supported yet.

**Comment by viirya** [comment]
I created the umbrella ticket https://github.com/apache/arrow-datafusion-comet/issues/240 to cover these unsupported expressions. I will add some expressions there so the people who are interested can work on.

**Review by sunchao — APPROVED** [review]

**Comment by viirya** [comment]
Merged. Thanks.

**Pull request merged**
