### PR TITLE
test: Add TPC-H test results

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #.

## Rationale for this change

We have already added back TPC-DS query results in #77. This adds back TPC-H query results.

## What changes are included in this PR?

Adds back TPC-H query results golden files to the repo. These files were generated using CometTPCHQuerySuite with Comet turned off, to make sure it is the same as Spark's results.

### CODE REVIEW

**Comment by viirya** [comment]
cc @sunchao @snmvaughan

**Review by snmvaughan — APPROVED** [review]
LGTM

**Review by sunchao — COMMENTED** [review]
Hmm why a few queries are missing in the results? q1, q15, q17, q18

**Comment by viirya** [comment]
Ah, yeah, they are disabled because the outputs are different to Spark. But for these output files, we should generate them. Let me add them.

**Review by sunchao — APPROVED** [review]

**Comment by viirya** [comment]
Merged. Thanks.

**Pull request merged**
