### PR TITLE
refactor: Skipping slicing on shuffle arrays in shuffle reader

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #.

## Rationale for this change

Because we have set shuffle batch size in shuffle writer, we don't need to slice shuffle arrays at shuffle reader now.

### CODE REVIEW

**Review by sunchao — COMMENTED** [review]
> Because we have set shuffle batch size in shuffle writer, we don't need to slice shuffle arrays at shuffle reader now.

Do you mean [here](https://github.com/apache/arrow-datafusion-comet/blob/main/core/src/execution/shuffle/row.rs#L3283)?

**Comment by viirya** [comment]
> > Because we have set shuffle batch size in shuffle writer, we don't need to slice shuffle arrays at shuffle reader now.
> 
> Do you mean [here](https://github.com/apache/arrow-datafusion-comet/blob/main/core/src/execution/shuffle/row.rs#L3283)?

Yea. Native shuffle writer also set batch size too.

**Comment by sunchao** [comment]
In that particular place, the batch size is configurable through `spark.comet.columnar.shuffle.batch.size`, which could be different from the batch size in other places. I'm not sure if this works in those cases.

**Comment by viirya** [comment]
> In that particular place, the batch size is configurable through `spark.comet.columnar.shuffle.batch.size`, which could be different from the batch size in other places. I'm not sure if this works in those cases.

Although it is a separate config, I think it should not be too far from the batch size. Actually I'm thinking if we can just use the batch size as the shuffle batch size to simplify them.

At least, I don't think we will set shuffle batch size larger than batch size (it doesn't make sense to me for the original purpose of the config). For a shuffle batch size smaller than batch size, there is even no reason to do slicing.

**Comment by sunchao** [comment]
Can we at least add some notes for that configuration? there is nothing stop the config from being set to a larger value than the batch size at the moment.

**Comment by viirya** [comment]
> Can we at least add some notes for that configuration? there is nothing stop the config from being set to a larger value than the batch size at the moment.

Okay. That is better.

**Review by sunchao — APPROVED** [review]

**Comment by viirya** [comment]
Merged. Thanks.

**Pull request merged**
