### PR TITLE
test: Reduce test time spent in `CometShuffleSuite`

### PR DESCRIPTION
**Pull request by sunchao**
## Which issue does this PR close?

Closes #.

## Rationale for this change

The Java CI now takes 70-90min to finish, and `CometShuffleSuite` is taking the majority it, of which a big portion is spent in various suites for encryption. Given a lot of the test cases are orthogonal to shuffle encryption, this PR moves the encryption suite into a separate class without extending `CometShuffleSuiteBase`.

## What changes are included in this PR?

Moves `CometShuffleEncryptionSuite` into a separate class with one test case, instead of run all the tests under `CometShuffleSuiteBase`.

### CODE REVIEW

**Comment by sunchao** [comment]
Hmm seeing some failures:

```
WARNING: /Users/runner/hostedtoolcache/Java_Adopt_jdk/17.0.10-7/x64/Contents/Home/bin/java is loading libcrypto in an unsafe way
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Comet Project Parent POM 0.1.0-SNAPSHOT:
[INFO] 
[INFO] Comet Project Parent POM ........................... SUCCESS [  8.062 s]
[INFO] comet-common ....................................... SUCCESS [01:00 min]
[INFO] comet-spark ........................................ FAILURE [07:35 min]
[INFO] comet-spark-integration ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:44 min
[INFO] Finished at: 2024-02-16T19:42:25Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.scalatest:scalatest-maven-plugin:2.0.2:test (test) on project comet-spark-spark3.4_2.12: There are test failures -> [Help 1]
```

Perhaps related to JDK 17

**Comment by viirya** [comment]
Looks like a warning only?

**Comment by sunchao** [comment]
Not sure. This is the only information I found. The tests just suddenly failed afterwards.

**Comment by sunchao** [comment]
It is something related to `libcrypto`. I'm trying to address it in https://github.com/apache/arrow-datafusion-comet/pull/41

**Comment by sunchao** [comment]
cc @viirya

**Review by viirya — APPROVED** [review]

**Comment by sunchao** [comment]
Thanks! merged

**Pull request merged**
