### PR TITLE
feat: Support Emit::First for SumDecimalGroupsAccumulator

### LINKED ISSUE #46: Support Emit::First for SumDecimalGroupsAccumulator
### What is the problem the feature request solves?

If the upstream operator of `HashAggregate` is sorted, `HashAggregate` will try to emit first groups if possible. Our custom `SumDecimalGroupsAccumulator` doesn't support `Emit::First`. So if  `Sort` is followed by `HashAggregate` and there is sum of decimal, the query will fail with:

```
        at std::backtrace::Backtrace::create(__internal__:0)                                                                                                                                                                           
        at comet::errors::init::{{closure}}(__internal__:0)                                                                                                                                                                            
        at std::panicking::rust_panic_with_hook(__internal__:0)                                                                                                                                                                        
        at std::panicking::begin_panic_handler::{{closure}}(__internal__:0)                                                                                                                                                            
        at std::sys_common::backtrace::__rust_end_short_backtrace(__internal__:0)                                                                                                                                                      
        at _rust_begin_unwind(__internal__:0)                                                                                                                                                                                          
        at core::panicking::panic_fmt(__internal__:0)                                                                                                                                                                                  
        at <comet::execution::datafusion::expressions::sum_decimal::SumDecimalGroupsAccumulator as datafusion_physical_expr::aggregate::groups_accumulator::GroupsAccumulator>::state(__internal__:0)                                  
        at datafusion_physical_plan::aggregates::row_hash::GroupedHashAggregateStream::emit(__internal__:0)                                                                                                                            
        at <datafusion_physical_plan::aggregates::row_hash::GroupedHashAggregateStream as futures_core::stream::Stream>::poll_next(__internal__:0)                                                                                     
        at <datafusion_physical_plan::aggregates::row_hash::GroupedHashAggregateStream as futures_core::stream::Stream>::poll_next(__internal__:0)                                                                                     
        at <datafusion_physical_plan::projection::ProjectionStream as futures_core::stream::Stream>::poll_next(__internal__:0)                                                                                                         
        at std::panicking::try::do_call(__internal__:0)                                                                                                                                                                                
        at _Java_org_apache_comet_Native_executePlan(__internal__:0)     
```

### Describe the potential solution

Support Emit::First for SumDecimalGroupsAccumulator

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #46.

## Rationale for this change

If the upstream operator of `HashAggregate` is sorted, `HashAggregate` will try to emit first groups if possible. Our custom `SumDecimalGroupsAccumulator` doesn't support `Emit::First`. So if  `Sort` is followed by `HashAggregate` and there is sum of decimal, the query will fail with:

```
        at std::backtrace::Backtrace::create(__internal__:0)                                                                                                                                                                           
        at comet::errors::init::{{closure}}(__internal__:0)                                                                                                                                                                            
        at std::panicking::rust_panic_with_hook(__internal__:0)                                                                                                                                                                        
        at std::panicking::begin_panic_handler::{{closure}}(__internal__:0)                                                                                                                                                            
        at std::sys_common::backtrace::__rust_end_short_backtrace(__internal__:0)                                                                                                                                                      
        at _rust_begin_unwind(__internal__:0)                                                                                                                                                                                          
        at core::panicking::panic_fmt(__internal__:0)                                                                                                                                                                                  
        at <comet::execution::datafusion::expressions::sum_decimal::SumDecimalGroupsAccumulator as datafusion_physical_expr::aggregate::groups_accumulator::GroupsAccumulator>::state(__internal__:0)                                  
        at datafusion_physical_plan::aggregates::row_hash::GroupedHashAggregateStream::emit(__internal__:0)                                                                                                                            
        at <datafusion_physical_plan::aggregates::row_hash::GroupedHashAggregateStream as futures_core::stream::Stream>::poll_next(__internal__:0)                                                                                     
        at <datafusion_physical_plan::aggregates::row_hash::GroupedHashAggregateStream as futures_core::stream::Stream>::poll_next(__internal__:0)                                                                                     
        at <datafusion_physical_plan::projection::ProjectionStream as futures_core::stream::Stream>::poll_next(__internal__:0)                                                                                                         
        at std::panicking::try::do_call(__internal__:0)                                                                                                                                                                                
        at _Java_org_apache_comet_Native_executePlan(__internal__:0)     
```

### CODE REVIEW

**Comment by viirya** [comment]
CI tests are passed. The failure is due to

```
WARNING: /Users/runner/hostedtoolcache/Java_Adopt_jdk/17.0.10-7/x64/Contents/Home/bin/java is loading libcrypto in an unsafe way
```

**Comment by sunchao** [comment]
@viirya I think you need to rebase this PR

**Comment by viirya** [comment]
Hmm, I think I already rebased on latest `main`.

**Comment by sunchao** [comment]
Hmm not sure. The same issue happened to https://github.com/apache/arrow-datafusion-comet/pull/40 and it is OK now after the rebasing.

**Comment by viirya** [comment]
I re-triggered the pipeline.

**Comment by viirya** [comment]
Hmm, it is actually flaky. Retriggered run is okay.

**Review by sunchao — APPROVED** [review]
LGTM. It might be better to add some details in PR description :)

**Comment by viirya** [comment]
Merged and added details in the PR description. Thanks.

**Pull request merged**
