### PR TITLE
fix: attempt to divide by zero error on decimal division

### LINKED ISSUE #171: `attempt to divide by zero` error on decimal division
### Describe the bug

An `attempt to divide by zero` error on decimal division happened on TPCDS q59 when working on SortMergeJoin.

```
  Cause: org.apache.comet.CometNativeException: attempt to divide by zero
        at std::backtrace::Backtrace::create(__internal__:0)
        at comet::errors::init::{{closure}}(__internal__:0)
        at std::panicking::rust_panic_with_hook(__internal__:0)
        at std::panicking::begin_panic::{{closure}}(__internal__:0)
        at std::sys_common::backtrace::__rust_end_short_backtrace(__internal__:0)
        at std::panicking::begin_panic(__internal__:0)
        at num_bigint::biguint::division::div_rem_ref(__internal__:0)
        at comet::execution::datafusion::expressions::scalar_funcs::create_comet_physical_fun::{{closure}}(__internal__:0)
        at <datafusion_physical_expr::scalar_function::ScalarFunctionExpr as datafusion_physical_expr::physical_expr::PhysicalExpr>::evaluate(__internal__:0)
        at <comet::execution::datafusion::expressions::checkoverflow::CheckOverflow as datafusion_physical_expr::physical_expr::PhysicalExpr>::evaluate(__internal__:0)
        at <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next(__internal__:0)
        at <datafusion_physical_plan::projection::ProjectionStream as futures_core::stream::Stream>::poll_next(__internal__:0)
        at comet::execution::jni_api::Java_org_apache_comet_Native_executePlan::{{closure}}(__internal__:0)
        at _Java_org_apache_comet_Native_executePlan(__internal__:0)
  at org.apache.comet.Native.executePlan(Native Method)
```

### Steps to reproduce

```scala
val decimalLiteral = Decimal(0.00)
df.select($"dec" / decimalLiteral).collect()
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #171.

### CODE REVIEW

**Comment by viirya** [comment]
cc @sunchao

**Comment by viirya** [comment]
cc @kazuyukitanimura

**Review by kazuyukitanimura — APPROVED** [review]
LGTM
I wonder if we need a similar fix for modulo operation

**Comment by viirya** [comment]
> LGTM I wonder if we need a similar fix for modulo operation

Thanks for review.

I think for modulo operation, we don't implement the operation in Comet but delegate to DataFusion?
I just tested it and looks okay. Let me also add it in the test.

**Comment by kazuyukitanimura** [comment]
Great, thanks for confirming

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by viirya** [comment]
Merged. Thanks.

**Pull request merged**
