### PR TITLE
build: Upgrade arrow-rs to 50.0.0 and DataFusion to 35.0.0

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #.

## What changes are included in this PR?

Upgrade arrow-rs to 50.0.0 and DataFusion to 35.0.0

### CODE REVIEW

**Review by viirya — COMMENTED** [review]
Note that we have newer versions of the two dependencies. But as we still have internal patches following this version upgrade, to ease the porting without resolving a lot of conflicts, we still port this.

**Comment by comphead** [comment]
Here is a migration to 36 if needed https://github.com/apache/arrow-datafusion-comet/pull/66

**Comment by viirya** [comment]
> Here is a migration to 36 if needed #66

Yea, we can merge it once we have ported all internal patches.

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by viirya** [comment]
Merged. Thanks.

**Pull request merged**
