### PR TITLE
fix: Remove duplicate byte array allocation for CometDictionary

### LINKED ISSUE #225: Duplicate byte array allocation in CometDictionary
### Describe the bug

During `initialize` call of `CometDictionary`, for decimal type, we call `getBinaryDecimal` on value array (`CometVector`) which copies bytes into an internal byte array of value array. Then we do copying the byte arrays again in `CometDictionary`.

Although we need to copy the bytes because byte array is reused, we only need one time copying here.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #225.

### CODE REVIEW

**Comment by viirya** [comment]
cc @sunchao @parthchandra

**Review by parthchandra — APPROVED** [review]
Good catch!

**Comment by parthchandra** [comment]
Also, FWIW, from memory profiling Comet while running TPC-DS, it appears that `CometVector.getDecimal` is a large (though not largest) contributor to memory allocation. This PR will not affect the memory usage, but should certainly speed things up a bit.

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by viirya** [comment]
Merged. Thanks.

**Pull request merged**
