### PR TITLE
test: Enable all remaining TPCDS queries

### LINKED ISSUE #74: Comet returns different results for 5 TPCDS queries compared with Spark
### Describe the bug

TPC-DS q34, q66, q64, q71, q88, q90, q96 are disabled right now because they generate different results from Spark.

q34 seems something to do with sorting. The order is different.
```
  java.lang.Exception: Expected "...NULL	NULL	NULL	NULL	[126143	15
NULL	NULL	NULL	NULL	21529]3	15
NULL	NULL	Mrs. ...", but got "...NULL	NULL	NULL	NULL	[215293	15
NULL	NULL	NULL	NULL	12614]3	15
NULL	NULL	Mrs. ..." Result did not match
```

q64 is also about sorting
```
  java.lang.Exception: Expected "...  	ation	35709     	[996       	NULL	Bridgeport	65817     	752       	Lakeview Lincoln	Friendship	74536     	1999	1	15.78	24.93	0.00	17.09	26.31	0.00	2000	1
ablepricallyantiought                             	ation	35709     	71        	River River	Friendship	34536     	NULL	NULL	Newport	NULL	1999	1	22.60	38.87	0.00	17.09	26.31	0.00	2000	1
...", but got "...  	ation	35709     	[71        	River River	Friendship	34536     	NULL	NULL	Newport	NULL	1999	1	22.60	38.87	0.00	17.09	26.31	0.00	2000	1
ablepricallyantiought                             	ation	35709     	996       	NULL	Bridgeport	65817     	752       	Lakeview Lincoln	Friendship	74536     	1999	1	15.78	24.93	0.00	17.09	26.31	0.00	2000	1
..." Result did not match
```

### Steps to reproduce

Enable these 3 queries in `CometTPCDSQuerySuite` and run the test suite.

### Expected behavior

Comet should produce the same query results as Spark for these 3 queries.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #74.

## Rationale for this change

I re-run `CometTPCDSQuerySuite` to generate query golden files. Looks like we committed incorrect content before as they are different to Spark's files. I re-checked them with Spark.

### CODE REVIEW

**Review by viirya — COMMENTED** [review]
This needs to be re-run after #252 is merged.

**Comment by viirya** [comment]
cc @andygrove @sunchao @parthchandra @comphead

**Review by sunchao — APPROVED** [review]
LGTM

**Comment by viirya** [comment]
Merged. Thanks.

**Pull request merged**
